USE [master]
GO

CREATE LOGIN [remoteuser] WITH PASSWORD=N'remotePass', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

ALTER SERVER ROLE [sysadmin] ADD MEMBER [remoteuser]
GO


